### ISSUE TITLE
ICMPExtension information not available

### ISSUE THREAD

**Issue by gdavila** [tracebox/tracebox#50] opened 2017-08-27 19:43 UTC
I cant get ICMPExtension information using  -v option as [json output suggest]( https://github.com/tracebox/tracebox#json-output-format). I'm using tracebox on macOS Sierra.

I also did not find the way to get the ICMPextensions using the [LUA API](http://www.tracebox.org/lua_doc/index.html). Is there any way?

 Here is an example of my output:
`$ sudo tracebox -j -v -p IP/UDP 104.19.193.102`
` ... { "hop": 6, "from": "200.89.161.77", "name": "77-161-89-200.fibertel.com.ar", "Modifications": [ { "IP::ExpCongestionNot": { "Expected": "0", "Received": "3" } }, { "IP::TTL": { "Expected": "6", "Received": "1" } }, { "IP::CheckSum": { "Expected": "0x2878", "Received": "0x4959" } } ], "Aditions": [ ], "Deletions": [ ] }, { "hop": 7, ...`

I've checked by using wireshark  that ICMP reply  200.89.161.77 (in the above example)  includes ICMP Multi-part extensions:
```
    ICMP Multi-Part Extensions
        Version: 2
        .... 0000 0000 0000 = Reserved: 0x0000
        Checksum: 0x1a02 [correct]
        MPLS Stack Entry
            Length: 8
            Class: 1
            C-Type: 1
            Label: 16188, Exp: 0, S: 1, TTL: 1
                0000 0011 1111 0011 1100 .... = Label: 16188
                .... .... .... .... .... 000. = Experimental: 0
                .... .... .... .... .... ...1 = Stack bit: Set
                Time to live: 1
```

**Comment by oliviertilmans** [comment] 2017-08-28 12:24
Hi,

I have no idea why the JSON documentation is out of sync with what the code does. I'd guess that it was a leftover from code the ones who wrote that part never published/merged.

We currently (and that code path is at least [4 years old](https://github.com/tracebox/tracebox/commit/81b1e75d01fc2a0cfa6b6c4a5261e5b69d8e7b13#diff-ff703963680e08beb3c319dbf6e0377cR259)) drop the ICMP extensions if any is found.
As these are supported by libcrafter, adding those in the json output should be fairly straightforward:
* Instead of trimming the packet/ignoring all extra layers, they should be stored in the PacketModification class
* [Extend Print_JSON to also output that new field](https://github.com/tracebox/tracebox/blob/master/src/tracebox/PacketModification.cc#L257)

The Lua API support would involve adding new wrappers to the ICMPExtensions set of classes from libcrafter.

I cannot do that this week, but can take a look at it after. Any PR before that would also be welcomed.

**Comment by oliviertilmans** [comment] 2017-08-29 14:43
@gdavila I found some free time to implement a basic support in the JSON/terminal output. It is however now yet exposed in the Lua API.

**Comment by gdavila** [comment] 2017-08-29 15:42
@oliviertilmans Thanks a lot for the support. Let me know any news regarding the Lua API implementation.

**Comment by gdavila** [comment] 2017-09-27 19:11
@oliviertilmans Hola

I've noticed the terminal output has an issue when icmp extensions are present. Actually, it prints the entire icmp message in hex format instead of just icmp extensions, i. e., 

`davila@ubuntuServer:~$ sudo tracebox  -v  ple2.det.uvigo.es`
`tracebox to 193.146.210.245 (ple2.det.uvigo.es): 64 hops max `
`1: 192.168.0.1 (192.168.0.1) 3ms `
`2: *`
`3: *`
`4: *`
`5: *`
`6: 81-161-89-200.fibertel.com.ar (200.89.161.81) 18ms  [PARTIAL] +PartialTCP < PartialTCP (4 bytes) :: SrcPort = 62502 , DstPort = 80 , SeqNumber = 3950968832 , >
 IP::ExpCongestionNot (0 -> 3) IP::TTL (6 -> 1) IP::CheckSum (0x33be -> 0x38bb) [Extra headers: < ICMPExtension (4 bytes) :: Version = 1 , Reserved = 2584 , CheckSum = 0x9df , >
 < ICMPExtensionObject (4 bytes) :: Length = 0 , ClassNum = 0 , CType = 0 , >
 < RawLayer (108 bytes) :: Payload = \x50\x2\x16\xd0\x2a\x82\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x20\x0\xd9\xea\x0\x8\x1\x1\x4\xb\x1\x1> ] `

However it works fine when icmp extensions have more than one mpls label:
`15: ae2.mx1.gen.ch.geant.net (62.40.98.153) 303ms IP::DiffServicesCP (0 -> 41) IP::ExpCongestionNot (0 -> 3) IP::TTL (15 -> 1) IP::CheckSum (0x2abe -> 0x3817) [Extra headers: < ICMPExtension (4 bytes) :: Version = 2 , Reserved = 0 , CheckSum = 0x64bc , >
 < ICMPExtensionObject (4 bytes) :: Length = 12 , ClassNum = 1 , CType = 1 , >
 < ICMPExtensionMPLS (4 bytes) :: Label = 299794 , Experimental = 0 , BottomOfStack = 0 , TTL = 1 , >
 < ICMPExtensionMPLS (4 bytes) :: Label = 17 , Experimental = 0 , BottomOfStack = 1 , TTL = 3 , >
`

Any clue to solve this issue?

**Comment by oliviertilmans** [comment] 2017-10-02 07:19
The fact that the whole extension is printed is due to the -v flag, as the extension is seen as a new inserted headers and the flag requires to report the exact difference (i.e. all new/changed/removed bytes).

Looking at this, you are likely hitting a libcrafter-related bug, as it fails to parse properly the ICMP Extensions (I doubt that `< ICMPExtensionObject (4 bytes) :: Length = 0 , ClassNum = 0 , CType = 0 , >` is actually what you received and the resulting RawLayer at the end indicates that it has no idea on what's included in the packet). It might be related to the ICMPExtension version ?

Could you  record on the side a packet capture while tracebox is running, to get all 'raw' icmp messages (e.g. `tcpdump -w record.pcap -i any icmp or icmp6`),

**Comment by gdavila** [comment] 2017-10-03 03:30
Hola,

I've captured a tracebox output. The ICMPExtension version on the pcap file is ok ( Version 2). So as you mentioned, tracebox output is not showing Extension properly. What I noticed is that **ICMP header** has a _"Length"_ field (Does that have sense?). (on the attached file you can find the entire capture and tracebox output)

Let me know your thoughts. 

Tracebox output for 7 hop:
```
7: 1-165-89-200.fibertel.com.ar (200.89.165.1) 10ms IP::ExpCongestionNot (0 -> 3) IP::TTL (7 -> 2) IP::CheckSum (0xe470 -> 0xe96d) [Extra headers: < ICMPExtension (4 bytes) :: Version = 0 , Reserved = 0 , CheckSum = 0x0 , >
 < ICMPExtensionObject (4 bytes) :: Length = 0 , ClassNum = 0 , CType = 0 , >
 < RawLayer (64 bytes) :: Payload = \x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x0\x20\x0\x38\x6\x0\x8\x1\x1\x5\xef\xa1\x1>
```
captured ICMP for 7 hop:
```
Internet Control Message Protocol
    Type: 11 (Time-to-live exceeded)
    Code: 0 (Time to live exceeded in transit)
    Checksum: 0x4b2c [correct]
    Length: 17
    [Length of original datagram: 68]
    Internet Protocol Version 4, Src: 192.168.0.242, Dst: 193.146.210.245
        0100 .... = Version: 4
        .... 0101 = Header Length: 20 bytes (5)
        Differentiated Services Field: 0x03 (DSCP: CS0, ECN: CE)
        Total Length: 40
        Identification: 0x393d (14653)
        Flags: 0x02 (Don't Fragment)
        Fragment offset: 0
        Time to live: 2
        Protocol: TCP (6)
        Header checksum: 0xe96d [validation disabled]
        Source: 192.168.0.242
        Destination: 193.146.210.245
        [Source GeoIP: Unknown]
        [Destination GeoIP: Unknown]
    Transmission Control Protocol, Src Port: 6665 (6665), Dst Port: 80 (80), Seq: 2099548939
        Source Port: 6665
        Destination Port: 80
        Sequence number: 2099548939
        [Stream index: 43]
        Sequence number: 2099548939    (relative sequence number)
        Acknowledgment number: 0
        Header Length: 20 bytes
        Flags: 0x002 (SYN)
        Window size value: 5840
        [Calculated window size: 5840]
        Checksum: 0x1867 [validation disabled]
        Urgent pointer: 0
    ICMP Multi-Part Extensions
        Version: 2
        .... 0000 0000 0000 = Reserved: 0x0000
        Checksum: 0x3806 [correct]
        MPLS Stack Entry
            Length: 8
            Class: 1
            C-Type: 1
            Label: 24314, Exp: 0, S: 1, TTL: 1
```

**Comment by oliviertilmans** [comment] 2017-10-03 08:27
Analyzing your trace, I think you hit:
https://github.com/pellegre/libcrafter/issues/46

i.e., the intermediate router does not set the length field of the ICMP message.
I'll try to allocate some time this week to work on that

**Closed** 2017-10-04 09:09 UTC

**Comment by oliviertilmans** [comment] 2017-10-04 09:11
Hi @gdavila,
The ICMP extension parsing issues should now be fixed. Please let me know (with the traces so I can debug it properly) if you observe other unexpected behaviors.
