### ISSUE TITLE
checking for Middlebox(testing for MPTCP) ?? but experiencing some difficulties  

### ISSUE THREAD

**Issue by AnsEMU** [tracebox/tracebox#43] opened 2015-06-01 06:46 UTC
After doing what cpaasch and Olivier Tilmans in order to use tracebox correctly, i get such a result : 

root@ENES:/home/enes# tracebox -n -p IP/TCP/MSS/MPCAPABLE/WSCALE bahn.de
tracebox to 81.200.198.6 (bahn.de): 64 hops max
1: 10.10.0.1  [PARTIAL] 
2: 193.140.41.10 IP::TTL IP::CheckSum 
3: 81.200.198.6 TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP -TCPOptionMPTCPCapable TCPOptionWindowScale::Shift 
any idea ?

**Comment by oliviertilmans** [comment] 2015-06-01 06:55
Fom that log, you see that you reach bahn.de in 3 hops,
  1. That hop sent a partial probe as ICMP payload (first 40 bytes), which were unmodified from the original probe
  2. That hop sent you a full copy of the received probe in the ICMP payload, where only the TLL/Checksum had changed (which is normal and to be expected)
  3. That hop appears to be bahn.de, as it changed the seq/ack numbers as well as the TCP flags and the IP's. However it does not appear to support MPTCP hence why it removed the MPCapable options. It also changed the window scale factor.

If you want to check for interference with mptcp, I'd advise you to try to send probes towards a mptcp enabled server (such as multipath-tcp.org) instead of bahn.de

**Comment by AnsEMU** [comment] 2015-06-01 06:58
Thanks for that !!! and this is for multipath-tcp.org
$ tracebox -n -p IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org
tracebox to 130.104.230.45 (multipath-tcp.org): 64 hops max
1: 10.10.0.1  [PARTIAL] 
2: 193.140.41.10 IP::TTL IP::CheckSum 
3: 130.104.230.45 TCP::SrcPort TCP::DstPort TCP::SeqNumber TCP::AckNumber TCP::DataOffset TCP::Flags TCP::CheckSum IP::TotalLength IP::Identification IP::TTL IP::CheckSum IP::SourceIP IP::DestinationIP -TCPOptionMPTCPCapable TCPOptionWindowScale::Shift 
root@ENES:/home/enes#

**Comment by oliviertilmans** [comment] 2015-06-01 07:11
Since you observe the same behavior, but this time towards and mptcp-enabled server, this means that there's a middlebox removing the mpcapable tcp option between 193.140.41.10 and 130.104.230.45 (the server).
As this trace looks abnormally short (you're supposed to cross e.g. 130.104.254.228), could you try to save a packet trace when performing the test? It looks like you're behind a NAT and I bet it is not handling the ICMP replies properly ... (or I broke the filters again in Tracebox, who knows)
e.g.
```bash
tcpdump -I any icmp -w capture.pcap &
TCPDUMP_PID=$!
tracebox -n -p IP/TCP/MSS/MPCAPABLE/WSCALE multipath-tcp.org
kill $TCPDUMP_PID
```
This will only save the icmp replies (if any) which are likely only caused by tracebox (and not your regular traffic).

**Comment by oliviertilmans** [comment] 2015-06-01 07:13
(You will then need to mail me the resulting capture.pcap file)

**Comment by oliviertilmans** [comment] 2015-06-01 12:11
Looks like to be the same than #44 as far the trace goes:
You are likely behind a TCP proxy located at 193.140.41.10, which could be stripping out the MPTCP options (or a middlebox after it, which we cannot detect due to the proxy).
I'm closing this, feel free to comment on the other issue if you have new elements.

**Closed by oliviertilmans** 2015-06-01 12:11 UTC

**Comment by AnsEMU** [comment] 2015-06-01 12:57
thanks
